[package]
name = "bevy_bevy"
version = "0.1.0"
edition = "2021"
description = "Bevy support for Bevy"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14"
